[scrapper_config]
within_time = "12h"
show_items = 8
[[scrapper_config.categories]]
category_name = "haugaland"
page_title = "Aktuelt Haugalandet"
page_title_horizontal = "SISTE PÂ AKTUELT HAUGALANDET"
keywords = ["Haugesund", "Karmøy", "Tysvær", "Sveio", "Utsira", "Bokn", "Vindafjord", "Etne", "Vikedal", "Suldal", "Sauda", "Karmsund", "Risøy", "Hasseløy", "Bakarøy", "Karmsundgata", "Spannavegen", "Bømlo", "Stord", "Fitjar", "Kvinnherad", "Bømlafjordtunnelen", "Bømlafjorden", "Langevåg", "Buavåg", "Leirvik", "Sagvåg", "Mastrafjordtunnelen", "Byfjordtunnelen", "Uføretunnelen", "Røldalstunnelen", "Seljestadtunnelen", "Bremnes", "Huglo", "Ølvesvegen", "Hatlestrand", "Håvika", "Sand", "Førlandsvegen", "Skjold", "Hardangervidda", "Haukelifjell", "Haukeli ", "Seljestad ", "Nordsjøen", "Nordsj", "ldalstunnelen", "Odda", "Ullensvang", "Hardanger", " Tyssedal", " Trolltunga", "#Stord", "Aker", "Solutions", "Eldøyane", "Kopervik", "#Kopervik", "Fotvatnet", ]

[[scrapper_config.categories]]
category_name = "sunnhordland"
page_title = "Aktuelt Sunnhordland"
page_title_horizontal = "SISTE PÂ AKTUELT SUNNHORDLAND"
keywords = ["Sveio", "Stord", "Bømlo", "Bømlafjorden", "Bømlabroa", "Bømlafjordtunnelen", "Fitjar", "Kvinnherad", "Leirvik", "Bremnesvegen", "Langevåg", "Buavåg", "Bremnes", "Huglo", "Ølvesvegen", "Hatlestrand", "Håvika", "Tysnes", ]

[[scrapper_config.categories]]
category_name = "test"
page_title = "test123"
page_title_horizontal = "test123"
keywords = ["test12", "test145", ]

[[scrapper_config.twitter_accounts]]
username = "politietsorvest"
prefix = "SISTE FRA POLITIET"
suffix = "(POLITIET/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "politivest"
prefix = "SISTE FRA POLITIET"
suffix = "(POLITIET/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "110SorVest"
prefix = "SISTE FRA BRANNVESENET"
suffix = "(110-SENTRALEN/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "110Vest"
prefix = "SISTE FRA BRANNVESENET"
suffix = "(110-SENTRALEN/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "VTSvest"
prefix = "TRAFIKK"
suffix = "(VEGVESEN/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "HRSSorNorge"
prefix = "REDNING"
suffix = "(HRSS/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "Meteorologene"
prefix = "VÆRET"
suffix = "(MET/RADIO HAUGALAND)"
