[scrapper_config]
within_time = "3"
show_items = 5
haugaland_keywords = [ "Haugesund", "Karmøy", "Tysvær", "Sveio", "Utsira", "Bokn", "Vindafjord", "Etne", "Vikedal", "Sandeid", "Sand", "Suldal", "Sauda", "Karmsund", "Risøy", "Hasseløy", "Bakarøy", "Karmsundgata", "Spannavegen", "Bømlo", "Stord", "Fitjar", "Kvinnherad", "Bømlafjordtunnelen", "Bømlafjorden", "Langevåg", "Buavåg", "Leirvik", "Sagvåg", "Mastrafjordtunnelen", "Byfjordtunnelen", "Uføretunnelen", "Røldalstunnelen", "Seljestadtunnelen", "Haukelitunnelen", "Bremnes", "Huglo",]
sunnhordland_keywords = [ "Sveio", "Stord", "Bømlo", "Bømlafjorden", "Bømlabroa", "Bømlafjordtunnelen", "Fitjar", "Kvinnherad", "Leirvik", "Bremnesvegen", "Langevåg", "Buavåg", "Bremnes", "Huglo",]

[[scrapper_config.twitter_accounts]]
username = "politietsorvest"
prefix = "SISTE FRA POLITIET"
suffix = "(POLITIET/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "politivest"
prefix = "SISTE FRA POLITIET"
suffix = "(POLITIET/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "110SorVest"
prefix = "SISTE FRA BRANNVESENET"
suffix = "(110-SENTRALEN/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "110Vest"
prefix = "SISTE FRA BRANNVESENET"
suffix = "(110-SENTRALEN/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "VTSvest"
prefix = "TRAFIKK"
suffix = "(VEGVESEN/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "HRSSorNorge"
prefix = "REDNING"
suffix = "(HRSS/RADIO HAUGALAND)"

[[scrapper_config.twitter_accounts]]
username = "Meteorologene"
prefix = "VÆRET"
suffix = "(MET/RADIO HAUGALAND)"
